backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-template",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: image }
          - {
              label: "Featured Image Alt",
              name: "featuredImageAlt",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: image }
          - {
              label: "Featured Image Alt",
              name: "featuredImageAlt",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/cookies/index.md"
        label: "Cookies Page"
        name: "cookies"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/privacy/index.md"
        label: "Privacy Page"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "categories"
    label: "Categories"
    create: false
    files:
      - file: "src/pages/categories/essay.md"
        label: "Essay"
        name: "essay"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "essay",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/categories/photo.md"
        label: "Photo"
        name: "photo"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "photo",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/categories/blog.md"
        label: "Blog"
        name: "blog"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "blog",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/categories/links.md"
        label: "Links"
        name: "links"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "links",
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "essay"
    label: "Essay"
    folder: "src/content/essay"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "essay",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - {
          label: "Featured Image Title",
          name: "featuredImageAlt",
          widget: "string",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "photo"
    label: "Photo"
    folder: "src/content/photo"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "photo",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - {
          label: "Featured Image Title",
          name: "featuredImageAlt",
          widget: "string",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "blog",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - {
          label: "Featured Image Title",
          name: "featuredImageAlt",
          widget: "string",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "links"
    label: "Links"
    folder: "src/content/links"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "links",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Website Name", name: "webname", widget: "string" }
      - { label: "Website Link", name: "path", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
