local_backend: true

backend:
  name: git-gateway
  branch: ver2.0
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_library:
  name: cloudinary
  config:
    cloud_name: bohok
    api_key: 783314219155448

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-template",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Homepage Image", name: "heroImage", widget: image }
          - {
              label: "Featured Image Alt",
              name: "featuredImageAlt",
              widget: "string",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/tentang-kami/index.md"
        label: "Tentang Kami"
        name: "tentangKami"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Featured Image", name: "featuredImage", widget: hidden }
          - {
              label: "Featured Image Alt",
              name: "featuredImageAlt",
              widget: hidden,
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/kontak/index.md"
        label: "Kontak"
        name: "kontak"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-template",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/kontak/terima-kasih/index.md"
        label: "Terima Kasih"
        name: "terimaKasih"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/cookies/index.md"
        label: "Cookies"
        name: "cookies"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/privasi/index.md"
        label: "Privasi"
        name: "privasi"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-template",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "categories"
    label: "Categories"
    create: false
    files:
      - file: "src/pages/esai/index.md"
        label: "Category Esai"
        name: "category-esai"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "esai",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/foto/index.md"
        label: "Category Foto"
        name: "category-foto"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "foto",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/blog/index.md"
        label: "Category Blog"
        name: "category-blog"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "blog",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/pranala/index.md"
        label: "Category Pranala"
        name: "category-pranala"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "category-template",
            }
          - {
              label: "Category",
              name: "category",
              widget: "hidden",
              default: "pranala",
            }
          - {
              label: "SEO",
              name: "SEO",
              widget: "object",
              fields:
                [
                  { label: "SEO Title", name: "SEOtitle", widget: "string" },
                  {
                    label: "SEO Description",
                    name: "SEOdescription",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "post-esai"
    label: "Post Esai"
    folder: "src/content/esai"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "esai",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - {
          label: "Featured Image Title",
          name: "featuredImageAlt",
          widget: "string",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "post-foto"
    label: "Post Foto"
    folder: "src/content/foto"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "foto",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - {
          label: "Featured Image Title",
          name: "featuredImageAlt",
          widget: "string",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "post-blog"
    label: "Post Blog"
    folder: "src/content/blog"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "blog",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredImage", widget: image }
      - {
          label: "Featured Image Title",
          name: "featuredImageAlt",
          widget: "string",
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "post-pranala"
    label: "Post Pranala"
    folder: "src/content/pranala"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-template",
        }
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "pranala",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Website Name", name: "webname", widget: "string" }
      - { label: "Website Link", name: "path", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
